# Generated by Django 4.0.10 on 2023-05-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_university'),
        ('projects', '0003_alter_job_job_begin_alter_job_job_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='student',
        ),
        migrations.AddField(
            model_name='job',
            name='student',
            field=models.ManyToManyField(null=True, to='accounts.student'),
        ),
    ]
