# Generated by Django 4.0.10 on 2023-05-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('WAITING', 'Waiting')], default='Waiting', max_length=8),
        ),
    ]
