# Generated by Django 4.0.10 on 2023-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REFUSED', 'Refused'), ('WAITING', 'Waiting')], default='WAITING', max_length=8),
        ),
    ]
