# Generated by Django 4.0.10 on 2023-05-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_notification_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='state',
        ),
    ]
