# Generated by Django 4.0.10 on 2023-05-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_rename_message_notification_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='state',
            field=models.CharField(choices=[('READ', 'Read'), ('UNREAD', 'Unread')], default='UNREAD', max_length=8),
        ),
    ]
