# Generated by Django 4.0.10 on 2023-05-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_notification_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='directed_to_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='Mensagem', max_length=100),
        ),
    ]
