# Generated by Django 4.0.10 on 2023-05-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_sum_avaliation_and_more'),
        ('projects', '0012_job_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='student',
            field=models.ManyToManyField(to='accounts.student'),
        ),
    ]
