# Generated by Django 4.0.10 on 2023-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_job_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover',
            field=models.ImageField(default='jobs/default_job.jpg', upload_to='jobs/'),
        ),
        migrations.AddField(
            model_name='project',
            name='cover',
            field=models.ImageField(default='projects/default_project.jpg', upload_to='projects/'),
        ),
    ]
