# Generated by Django 4.0.10 on 2023-05-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ong',
            name='cnpj',
            field=models.CharField(default='0', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='registration',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
