# Generated by Django 4.0.10 on 2023-05-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfil',
            field=models.ImageField(blank=True, upload_to='perfils/'),
        ),
    ]
