# Generated by Django 4.0.10 on 2023-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_cover_customuser_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(default='default_cover.jpg', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.ImageField(default='default_perfil.jpg', upload_to='perfils/'),
        ),
    ]
