# Generated by Django 4.0.10 on 2023-05-25 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_cover_alter_customuser_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(default='default_cover.png', upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='perfil',
            field=models.ImageField(default='default_perfil.png', upload_to='perfils/'),
        ),
    ]
