# Generated by Django 4.0.10 on 2023-05-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_cover_alter_customuser_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sum_avaliation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_avaliation',
            field=models.IntegerField(default=0),
        ),
    ]
