# Generated by Django 4.0.10 on 2023-05-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_comment_avaliation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='avaliation',
            new_name='stars',
        ),
    ]
